export const LASTFM_PAGE_SIZE = 200;
export const LASTFM_MAX_PUBLIC_PAGES = 500;
export const LASTFM_MAX_PUBLIC_SCROBBLES =
  LASTFM_PAGE_SIZE * LASTFM_MAX_PUBLIC_PAGES;
export const LASTFM_USERNAME_MAX_LENGTH = 15;
