export const SPOTIFY_MAX_COMPRESSED_MEGABYTES = 100;
export const SPOTIFY_MAX_COMPRESSED_BYTES =
  SPOTIFY_MAX_COMPRESSED_MEGABYTES * 1024 * 1024;
export const SPOTIFY_MAX_EXPANDED_BYTES = 512 * 1024 * 1024;
export const SPOTIFY_MAX_JSON_BYTES = 128 * 1024 * 1024;
export const SPOTIFY_MAX_JSON_FILES = 100;
export const SPOTIFY_MAX_ARCHIVE_ENTRIES = 500;
export const SPOTIFY_MAX_COMPRESSION_RATIO = 100;
export const SPOTIFY_MAX_EVENTS = 750_000;
export const SPOTIFY_MAX_TEXT_LENGTH = 500;
export const SPOTIFY_MAX_REASON_LENGTH = 100;
export const SPOTIFY_MAX_TIMESTAMP_LENGTH = 64;
export const SPOTIFY_MAX_PROCESSING_MS = 120_000;
